"""Initial config

Revision ID: 0409c652f4f7
Revises: 
Create Date: 2026-03-04 12:33:01.866284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0409c652f4f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('guild_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('heroes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('Tank', 'Carry', 'Support', 'Control', name='herorole'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('is_in_team', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rarity', sa.Enum('C', 'B', 'A', 'S', name='portalrarity'), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_generation_rate', sa.Integer(), nullable=True),
    sa.Column('controlling_guild_id', sa.String(), nullable=True),
    sa.Column('controlling_player_id', sa.String(), nullable=True),
    sa.Column('defender_1_id', sa.String(), nullable=True),
    sa.Column('defender_2_id', sa.String(), nullable=True),
    sa.Column('defender_3_id', sa.String(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['controlling_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['controlling_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['defender_1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['defender_2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['defender_3_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portal_id', sa.String(), nullable=True),
    sa.Column('attacker_guild_id', sa.String(), nullable=True),
    sa.Column('attacker_player_id', sa.String(), nullable=True),
    sa.Column('defender_guild_id', sa.String(), nullable=True),
    sa.Column('defender_player_id', sa.String(), nullable=True),
    sa.Column('attacker_1_id', sa.String(), nullable=True),
    sa.Column('attacker_2_id', sa.String(), nullable=True),
    sa.Column('attacker_3_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Resolved', name='battlestatus'), nullable=True),
    sa.Column('winner_guild_id', sa.String(), nullable=True),
    sa.Column('winner_player_id', sa.String(), nullable=True),
    sa.Column('combat_log', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['attacker_2_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['attacker_3_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['attacker_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['attacker_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['defender_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['defender_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.ForeignKeyConstraint(['winner_guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['winner_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battles')
    op.drop_table('portals')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_table('guilds')
    # ### end Alembic commands ###
