"""add_expires_at_to_gacha_banners

Revision ID: 15d50918acfa
Revises: fa4_progression_v1
Create Date: 2026-03-23 18:11:01.329457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15d50918acfa'
down_revision: Union[str, Sequence[str], None] = 'fa4_progression_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_name'), 'clans', ['name'], unique=True)
    op.create_table('clan_boss_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('clan_id', sa.String(), nullable=False),
    sa.Column('boss_name', sa.String(), nullable=True),
    sa.Column('boss_max_hp', sa.Integer(), nullable=True),
    sa.Column('boss_current_hp', sa.Integer(), nullable=True),
    sa.Column('boss_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Defeated', name='clanbossstatus'), nullable=True),
    sa.Column('week_start', sa.DateTime(), nullable=True),
    sa.Column('week_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clan_boss_damage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('damage_dealt', sa.Integer(), nullable=True),
    sa.Column('attacks_used', sa.Integer(), nullable=True),
    sa.Column('last_attack_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['clan_boss_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_commanders',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('order_class', sa.Enum('FlameInquisitor', 'EtherChronist', 'SpectralBlade', 'StoneCleric', 'LunarHunter', name='playerorderclass'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('active_basic_id', sa.String(), nullable=True),
    sa.Column('active_active_id', sa.String(), nullable=True),
    sa.Column('active_ultimate_id', sa.String(), nullable=True),
    sa.Column('active_passive_id', sa.String(), nullable=True),
    sa.Column('team_slot', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.drop_table('player_avatars')
    op.drop_index(op.f('ix_guilds_name'), table_name='guilds')
    op.drop_table('guilds')
    op.alter_column('arena_matches', 'combat_log',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('battles', sa.Column('attacker_clan_id', sa.String(), nullable=True))
    op.add_column('battles', sa.Column('defender_clan_id', sa.String(), nullable=True))
    op.add_column('battles', sa.Column('winner_clan_id', sa.String(), nullable=True))
    op.alter_column('battles', 'combat_log',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('battles_attacker_guild_id_fkey'), 'battles', type_='foreignkey')
    op.drop_constraint(op.f('battles_defender_guild_id_fkey'), 'battles', type_='foreignkey')
    op.drop_constraint(op.f('battles_winner_guild_id_fkey'), 'battles', type_='foreignkey')
    op.create_foreign_key(None, 'battles', 'clans', ['winner_clan_id'], ['id'])
    op.create_foreign_key(None, 'battles', 'clans', ['defender_clan_id'], ['id'])
    op.create_foreign_key(None, 'battles', 'clans', ['attacker_clan_id'], ['id'])
    op.drop_column('battles', 'defender_guild_id')
    op.drop_column('battles', 'attacker_guild_id')
    op.drop_column('battles', 'winner_guild_id')
    op.add_column('campaign_stages', sa.Column('world_number', sa.Integer(), nullable=True))
    op.add_column('campaign_stages', sa.Column('afk_clan_coins_per_hour', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_equipment_hero_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_player_id'), table_name='equipment')
    op.drop_constraint(op.f('equipment_hero_id_fkey'), 'equipment', type_='foreignkey')
    op.drop_constraint(op.f('equipment_player_id_fkey'), 'equipment', type_='foreignkey')
    op.create_foreign_key(None, 'equipment', 'heroes', ['hero_id'], ['id'])
    op.create_foreign_key(None, 'equipment', 'players', ['player_id'], ['id'])
    op.add_column('gacha_banners', sa.Column('soft_pity_start', sa.Integer(), nullable=True))
    op.add_column('gacha_banners', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('gacha_banners', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.alter_column('guardian_spirits', 'player_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guardian_spirits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guardian_spirits', 'element',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Fogo'::character varying"))
    op.alter_column('guardian_spirits', 'rarity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guardian_spirits', 'passive_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('guardian_spirits', 'passive_description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_column('guardian_spirits', 'chase_trigger')
    op.drop_column('guardian_spirits', 'damage_multiplier')
    op.drop_column('guardian_spirits', 'chase_effect')
    op.add_column('heroes', sa.Column('breakthrough_level', sa.Integer(), nullable=True))
    op.add_column('heroes', sa.Column('breakthrough_fragments', sa.Integer(), nullable=True))
    op.add_column('player_banner_states', sa.Column('guaranteed_next', sa.Boolean(), nullable=True))
    op.add_column('player_progress', sa.Column('daily_boss_attacks_remaining', sa.Integer(), nullable=True))
    op.add_column('player_wallets', sa.Column('clan_coins', sa.Integer(), nullable=True))
    op.add_column('player_wallets', sa.Column('spirit_tickets', sa.Integer(), nullable=True))
    op.drop_column('player_wallets', 'guild_coins')
    op.add_column('players', sa.Column('clan_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('players_guild_id_fkey'), 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'clans', ['clan_id'], ['id'])
    op.drop_column('players', 'guild_id')
    op.add_column('portals', sa.Column('map_x', sa.Float(), nullable=True))
    op.add_column('portals', sa.Column('map_y', sa.Float(), nullable=True))
    op.add_column('portals', sa.Column('controlling_clan_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('portals_controlling_guild_id_fkey'), 'portals', type_='foreignkey')
    op.create_foreign_key(None, 'portals', 'clans', ['controlling_clan_id'], ['id'])
    op.drop_column('portals', 'controlling_guild_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portals', sa.Column('controlling_guild_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'portals', type_='foreignkey')
    op.create_foreign_key(op.f('portals_controlling_guild_id_fkey'), 'portals', 'guilds', ['controlling_guild_id'], ['id'])
    op.drop_column('portals', 'controlling_clan_id')
    op.drop_column('portals', 'map_y')
    op.drop_column('portals', 'map_x')
    op.add_column('players', sa.Column('guild_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key(op.f('players_guild_id_fkey'), 'players', 'guilds', ['guild_id'], ['id'])
    op.drop_column('players', 'clan_id')
    op.add_column('player_wallets', sa.Column('guild_coins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player_wallets', 'spirit_tickets')
    op.drop_column('player_wallets', 'clan_coins')
    op.drop_column('player_progress', 'daily_boss_attacks_remaining')
    op.drop_column('player_banner_states', 'guaranteed_next')
    op.drop_column('heroes', 'breakthrough_fragments')
    op.drop_column('heroes', 'breakthrough_level')
    op.add_column('guardian_spirits', sa.Column('chase_effect', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('guardian_spirits', sa.Column('damage_multiplier', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('guardian_spirits', sa.Column('chase_trigger', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('guardian_spirits', 'passive_description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('guardian_spirits', 'passive_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('guardian_spirits', 'rarity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guardian_spirits', 'element',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Fogo'::character varying"))
    op.alter_column('guardian_spirits', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guardian_spirits', 'player_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('gacha_banners', 'expires_at')
    op.drop_column('gacha_banners', 'is_active')
    op.drop_column('gacha_banners', 'soft_pity_start')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.create_foreign_key(op.f('equipment_player_id_fkey'), 'equipment', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('equipment_hero_id_fkey'), 'equipment', 'heroes', ['hero_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_equipment_player_id'), 'equipment', ['player_id'], unique=False)
    op.create_index(op.f('ix_equipment_hero_id'), 'equipment', ['hero_id'], unique=False)
    op.drop_column('campaign_stages', 'afk_clan_coins_per_hour')
    op.drop_column('campaign_stages', 'world_number')
    op.add_column('battles', sa.Column('winner_guild_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('battles', sa.Column('attacker_guild_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('battles', sa.Column('defender_guild_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.create_foreign_key(op.f('battles_winner_guild_id_fkey'), 'battles', 'guilds', ['winner_guild_id'], ['id'])
    op.create_foreign_key(op.f('battles_defender_guild_id_fkey'), 'battles', 'guilds', ['defender_guild_id'], ['id'])
    op.create_foreign_key(op.f('battles_attacker_guild_id_fkey'), 'battles', 'guilds', ['attacker_guild_id'], ['id'])
    op.alter_column('battles', 'combat_log',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('battles', 'winner_clan_id')
    op.drop_column('battles', 'defender_clan_id')
    op.drop_column('battles', 'attacker_clan_id')
    op.alter_column('arena_matches', 'combat_log',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('guilds',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guilds_pkey'))
    )
    op.create_index(op.f('ix_guilds_name'), 'guilds', ['name'], unique=True)
    op.create_table('player_avatars',
    sa.Column('player_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('avatar_class', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_basic_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active_ultimate_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active_passive_1_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active_passive_2_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_slot', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('player_avatars_player_id_fkey')),
    sa.PrimaryKeyConstraint('player_id', name=op.f('player_avatars_pkey'))
    )
    op.drop_table('player_commanders')
    op.drop_table('clan_boss_damage')
    op.drop_table('clan_boss_sessions')
    op.drop_index(op.f('ix_clans_name'), table_name='clans')
    op.drop_table('clans')
    # ### end Alembic commands ###
