"""Add CampaignStage and PlayerProgress models

Revision ID: 222d090efa3c
Revises: 0409c652f4f7
Create Date: 2026-03-04 17:46:59.064939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222d090efa3c'
down_revision: Union[str, Sequence[str], None] = '0409c652f4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('difficulty_modifier', sa.Integer(), nullable=True),
    sa.Column('afk_xp_per_hour', sa.Integer(), nullable=True),
    sa.Column('afk_gold_per_hour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_stages_stage_number'), 'campaign_stages', ['stage_number'], unique=True)
    op.create_table('player_progress',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('highest_stage_number', sa.Integer(), nullable=True),
    sa.Column('last_afk_collection', sa.DateTime(), nullable=True),
    sa.Column('daily_sweeps_remaining', sa.Integer(), nullable=True),
    sa.Column('daily_fast_rewards_remaining', sa.Integer(), nullable=True),
    sa.Column('last_daily_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_progress')
    op.drop_index(op.f('ix_campaign_stages_stage_number'), table_name='campaign_stages')
    op.drop_table('campaign_stages')
    # ### end Alembic commands ###
