"""fase_10_advanced_combat_mechanics

Revision ID: 715b519343d7
Revises: 9a4a1fef9aa4
Create Date: 2026-03-09 17:59:54.850281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '715b519343d7'
down_revision: Union[str, Sequence[str], None] = '9a4a1fef9aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('hit_count', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('apply_status', sa.Enum('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', 'Stun', 'Silence', 'Blind', 'Root', 'Burn', 'Poison', 'Bleed', 'Shield', name='combatstatuseffect'), nullable=True))
    op.add_column('skills', sa.Column('advance_amount', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('delay_amount', sa.Integer(), nullable=True))
    op.add_column('skills', sa.Column('max_chases_per_turn', sa.Integer(), nullable=True))
    op.alter_column('skills', 'chase_trigger',
               existing_type=postgresql.ENUM('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', name='combatstatuseffect'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'chase_trigger',
               existing_type=sa.String(),
               type_=postgresql.ENUM('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', name='combatstatuseffect'),
               existing_nullable=True)
    op.drop_column('skills', 'max_chases_per_turn')
    op.drop_column('skills', 'delay_amount')
    op.drop_column('skills', 'advance_amount')
    op.drop_column('skills', 'apply_status')
    op.drop_column('skills', 'hit_count')
    # ### end Alembic commands ###
