"""Add Phase 5 Arena and Death CD

Revision ID: 7dc8f1676df5
Revises: 222d090efa3c
Create Date: 2026-03-04 17:54:16.695842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc8f1676df5'
down_revision: Union[str, Sequence[str], None] = '222d090efa3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attacker_player_id', sa.String(), nullable=True),
    sa.Column('defender_player_id', sa.String(), nullable=True),
    sa.Column('attacker_points_before', sa.Integer(), nullable=True),
    sa.Column('defender_points_before', sa.Integer(), nullable=True),
    sa.Column('winner_player_id', sa.String(), nullable=True),
    sa.Column('points_exchanged', sa.Integer(), nullable=True),
    sa.Column('combat_log', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['defender_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('heroes', sa.Column('death_cooldown_until', sa.DateTime(), nullable=True))
    op.add_column('player_progress', sa.Column('arena_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_progress', 'arena_points')
    op.drop_column('heroes', 'death_cooldown_until')
    op.drop_table('arena_matches')
    # ### end Alembic commands ###
