"""Add Phase 7 PlayerWallet

Revision ID: 875a759c2699
Revises: f7b37ce2fb29
Create Date: 2026-03-04 18:13:20.709655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875a759c2699'
down_revision: Union[str, Sequence[str], None] = 'f7b37ce2fb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_wallets',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('crystals_premium', sa.Integer(), nullable=True),
    sa.Column('guild_coins', sa.Integer(), nullable=True),
    sa.Column('summon_tickets', sa.Integer(), nullable=True),
    sa.Column('pity_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_wallets')
    # ### end Alembic commands ###
