"""fase_10_gacha_banners

Revision ID: 9a4a1fef9aa4
Revises: cba6f4ae06ae
Create Date: 2026-03-05 16:35:11.667924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4a1fef9aa4'
down_revision: Union[str, Sequence[str], None] = 'cba6f4ae06ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gacha_banners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('faction_focus', sa.Enum('Vanguard', 'Arcane', 'Shadow', 'Neutral', name='herofaction'), nullable=True),
    sa.Column('cost_amount', sa.Integer(), nullable=True),
    sa.Column('cost_currency', sa.String(), nullable=True),
    sa.Column('hard_pity_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_banner_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('banner_id', sa.String(), nullable=True),
    sa.Column('pity_counter_sss', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['banner_id'], ['gacha_banners.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Explicitly create the ENUM for rarity since add_column does not emit CREATE TYPE automatically
    op.execute("CREATE TYPE herorarity AS ENUM ('SSS', 'SS', 'S', 'A', 'B');")
    
    op.add_column('heroes', sa.Column('faction', sa.Enum('Vanguard', 'Arcane', 'Shadow', 'Neutral', name='herofaction'), nullable=True))
    op.add_column('heroes', sa.Column('rarity', sa.Enum('SSS', 'SS', 'S', 'A', 'B', name='herorarity'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'rarity')
    op.drop_column('heroes', 'faction')
    op.drop_table('player_banner_states')
    op.drop_table('gacha_banners')
    # ### end Alembic commands ###
