"""fase_10_5_avatar_and_summons

Revision ID: 9c96d635287b
Revises: 715b519343d7
Create Date: 2026-03-09 18:05:37.532578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c96d635287b'
down_revision: Union[str, Sequence[str], None] = '715b519343d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_spirits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('is_equipped', sa.Boolean(), nullable=True),
    sa.Column('chase_trigger', sa.String(), nullable=True),
    sa.Column('chase_effect', sa.String(), nullable=True),
    sa.Column('damage_multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_avatars',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('avatar_class', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('active_basic_id', sa.String(), nullable=True),
    sa.Column('active_ultimate_id', sa.String(), nullable=True),
    sa.Column('active_passive_1_id', sa.String(), nullable=True),
    sa.Column('active_passive_2_id', sa.String(), nullable=True),
    sa.Column('team_slot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_avatars')
    op.drop_table('guardian_spirits')
    # ### end Alembic commands ###
