"""phase9

Revision ID: cba6f4ae06ae
Revises: 875a759c2699
Create Date: 2026-03-05 14:27:51.473527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba6f4ae06ae'
down_revision: Union[str, Sequence[str], None] = '875a759c2699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('team_slot', sa.Integer(), nullable=True))
    op.add_column('heroes', sa.Column('base_launcher_chance', sa.Float(), nullable=True))
    op.add_column('heroes', sa.Column('base_launcher_status', sa.Enum('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', name='combatstatuseffect'), nullable=True))
    op.drop_column('heroes', 'is_in_team')
    op.add_column('skills', sa.Column('launcher_status', sa.Enum('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', name='combatstatuseffect'), nullable=True))
    op.add_column('skills', sa.Column('chase_trigger', sa.Enum('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', name='combatstatuseffect'), nullable=True))
    op.add_column('skills', sa.Column('chase_effect', sa.Enum('NoneEffect', 'Knockdown', 'HighFloat', 'LowFloat', 'Repulse', name='combatstatuseffect'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'chase_effect')
    op.drop_column('skills', 'chase_trigger')
    op.drop_column('skills', 'launcher_status')
    op.add_column('heroes', sa.Column('is_in_team', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('heroes', 'base_launcher_status')
    op.drop_column('heroes', 'base_launcher_chance')
    op.drop_column('heroes', 'team_slot')
    # ### end Alembic commands ###
