"""Add Phase 6 Skills

Revision ID: f7b37ce2fb29
Revises: 7dc8f1676df5
Create Date: 2026-03-04 17:57:42.476261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b37ce2fb29'
down_revision: Union[str, Sequence[str], None] = '7dc8f1676df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hero_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('skill_type', sa.Enum('Basic', 'Active', 'Ultimate', 'Passive', name='skilltype'), nullable=True),
    sa.Column('cooldown', sa.Integer(), nullable=True),
    sa.Column('energy_cost', sa.Integer(), nullable=True),
    sa.Column('effect_type', sa.Enum('Damage', 'Heal', 'Taunt', 'Buff', name='effecttype'), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('heroes', sa.Column('max_mana', sa.Integer(), nullable=True))
    op.add_column('heroes', sa.Column('current_mana', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('heroes', 'current_mana')
    op.drop_column('heroes', 'max_mana')
    op.drop_table('skills')
    # ### end Alembic commands ###
